services:
  traefik:
    networks:
      - AuthFrontNet
      - GuacFrontNet
      
  whoami:
    labels:
      - "traefik.http.routers.whoami.middlewares=authentik@file"

  auth-server:
    ports: []
    expose:
      - "9000"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=AuthFrontNet"

  guac:
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${shrooGuacName}FrontNet"
      - "traefik.http.routers.guac-rt.middlewares=guac-mwr@file"
