services:
  traefik:
    networks:
      - AuthFrontNet
      - GuacFrontNet
      
  whoami:
    labels:
      - "traefik.http.routers.whoami.middlewares=auth-mwr@file"

  auth-server:
    expose:
      - "9000"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=AuthFrontNet"

  guac:
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=GuacFrontNet"
      - "traefik.http.routers.guac-rt.middlewares=guac-mwr@file"
