services:
  traefik:
    networks:
      - AuthFrontNet
      - GuacFrontNet
      
  whoami:
    labels:
      - "traefik.http.routers.whoami.middlewares=authentik@file"

  auth-server:
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=AuthFrontNet"

  guacamole:
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=GuacFrontNet"
      #- "traefik.http.routers.whoami.middlewares=authentik@file"

