x-user: &user
  user: "$shroober"

services:
  traefik:
    <<: *user
    networks:
      - AuthFrontNet
      - GuacFrontNet
      
  whoami:
    <<: *user
    labels:
      - "traefik.http.routers.whoami.middlewares=authentik@file"

  auth-server:
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=AuthFrontNet"

  auth-worker:
    <<: *user

  auth-pg:
    <<: *user
    
  auth-redis:
    <<: *user
    
  guac:
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=GuacFrontNet"
      - "traefik.http.routers.guac-rt.middlewares=guac-mwr@file"
