services:
  guacd:
    container_name: "guacd"
    image: "docker.io/guacamole/guacd"
    networks:
      - GuacOutNet
      - GuacBackNet
    volumes:
      - "${shrooGuacDir}/drive:/drive:rw"
      - "${shrooGuacDir}/record:/record:rw"
    restart: always

  guac-pg:
    container_name: "${shrooGuacName}-pg"
    image: "docker.io/library/postgres:16-alpine"
    env_file:
      - "${shrooGuacDir}/.guac-pg.env"
    #user: "$shroober"
    networks:
      - GuacBackNet
    volumes:
      - "${shrooGuacDB}/init:/docker-entrypoint-initdb.d:z"
      - "${shrooGuacDB}/data:/var/lib/postgresql/data:Z"
    restart: always

  guac:
    container_name: "${shrooGuacName}"
    image: "docker.io/guacamole/guacamole"
    env_file:
      - "${shrooGuacDir}/.guac.env"
    ports:
      - "8080/tcp"
    networks:
      - GuacFrontNet
      - GuacBackNet
    volumes:
      - "${shrooGuacDir}/record:/record:rw"
    restart: always
    depends_on:
      guacd:
        condition: service_healthy
      guac-pg:
        condition: service_healthy

networks:
  GuacOutNet:
    name: GuacOutNet
    driver: bridge
    internal: false 
  GuacFrontNet:
    name: GuacFrontNet
    driver: bridge
    internal: false 
  GuacBackNet:  
    name: GuacBackNet
    driver: bridge
    internal: true