services:
  guacd:
    container_name: guacd
    image: docker.io/guacamole/guacd
    user: "$shroober"
    networks:
      - GuacOutNet
      - GuacBackNet
    volumes:
      - ${shrooGuacDir}/drive:/drive:rw
      - ${shrooGuacDir}/record:/record:rw
    restart: always

  guac-pg:
    container_name: guac-pg
    image: docker.io/library/postgres:16-alpine
    env_file:
      - ${shrooGuacDir}/.guac-pg.env
    user: "$shroober"
    networks:
      - GuacBackNet
    volumes:
      - ${shrooGuacDB}/init:/docker-entrypoint-initdb.d:z
      - ${shrooGuacDB}/data:/var/lib/postgresql/data:Z
    restart: always

  guac:
    container_name: guac
    image: docker.io/guacamole/guacamole
    env_file:
      - ${shrooGuacDir}/.guac.env
    user: "$shroober"
    ports:
      - 8080/tcp
    networks:
      - GuacFrontNet
      - GuacBackNet
    volumes:
      - ${shrooGuacDir}/record:/record:rw
    restart: always
    depends_on:
      - guacd
      - guac-pg

networks:
  GuacOutNet:
    name: GuacOutNet
    driver: bridge
    internal: false 
  GuacFrontNet:
    name: GuacFrontNet
    driver: bridge
    internal: false 
  GuacBackNet:  
    name: GuacBackNet
    driver: bridge
    internal: true
