http:
  routers:
    dashboard:
      middlewares:
        - "dashboard_redirect"
        - "dashboard_stripprefix"
      service: "dashboard@internal"
      rule: 'Host(`traefik.{{env "DOMAIN_NAME"}}`) && PathPrefix(`/`)'
      priority: 1000
      tls:
        domains:
          - main: '{{env "DOMAIN_NAME"}}'
            sans:
              - '*.{{env "DOMAIN_NAME"}}'
    api:
      service: "api@internal"
      rule: 'Host(`traefik.{{env "DOMAIN_NAME"}}`) && PathPrefix(`/api`)'
      priority: 1001
      
  middlewares:
    dashboard_redirect:
      redirectRegex:
        regex: ^(http:\/\/([[\w:.]+]|[\w._-]+)(:\d+)?)\/$
        replacement: "${1}/dashboard/"
        permanent: true
    dashboard_stripprefix:
      stripPrefix:
        prefixes:
          - "/dashboard/"
          - "/dashboard"
