services:
  traefik:
    container_name: "$shrooRPName"
    image: "docker.io/traefik:v3.1"
    env_file:
      - "${shrooRPDir}/.traefik.env"
    ports:
      - "8080:80"
      - "8443:443"
    networks:
      - ReverseProxyNet
    volumes:
      - "${shrooSocket}:/var/run/docker.sock:ro"
      - "${shrooRPDir}/letsencrypt:/letsencrypt"
      - "${shrooRPDir}/traefik.yml:/etc/traefik/traefik.yml"
      - "${shrooRPDir}/dynamic:/dynamic"
      - "${shrooRPLogDir}:/var/log/traefik/"
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  whoami:
    container_name: "whoami"
    image: "docker.io/traefik/whoami"
    networks:
      - ReverseProxyNet
    labels:
      - "traefik.enable=true"

networks:
  ReverseProxyNet:
    name: ReverseProxyNet
    driver: bridge
    internal: false