################################################################
# Global configuration
################################################################
global:
  checkNewVersion: true
  sendAnonymousUsage: false

################################################################
# Entrypoints configuration
################################################################
entryPoints:
  web: # entrypoint name
    address: :80 # entrypoint address
    http:
      redirections: # redirectScheme middleware
        entryPoint:
          to: "websecure" # name of entrypoint to redirect to
          scheme: "https" # scheme used after redirection
  websecure:
    address: :443
    asDefault: true # entrypoint set as default
    http:
      tls: # tls enabled by default for the above entrypoint
        certResolver: "letsencrypt" # default certificate resolver

################################################################
# Let's Encrypt
################################################################
certificatesresolvers:
  letsencrypt: # certResolver name
    acme:
      email: "{{env \"PROVIDER_EMAIL\"}}" # email provided by an environment variable
      storage: "/letsencrypt/acme.json" # storage location for the acme.json
      preferredchain: 'ISRG Root X2'
      keytype: 'ECDSA P-384'
      dnsChallenge: # challenge type
        provider: "{{env \"PROVIDER\"}}" # provider code provided by an environment variable
        
################################################################
# Traefik logs configuration
################################################################        
accessLog:
  addInternals: true # adding logging for api and dashboard services
  filePath: "/var/log/traefik/access.log" # storage location for accessLog

log:
  level: "ERROR"
  filePath: "/var/log/traefik/traefik.log" # storage location for logs
  format: "json"

################################################################
# API, dashboard and ping configuration
################################################################
api:
  insecure: false
  dashboard: true

ping:
  entryPoint: "web"

################################################################
# Docker configuration backend
################################################################
providers:
  docker:
    exposedByDefault: false # label "traefik.enable=true" needed to expose a container
    defaultRule: "Host(`{{ .ContainerName }}.{{env \"DOMAIN_NAME\"}}`)" # default rule for exposed containers is [containername].[domainName]
    
  file:
    directory: "/etc/traefik/dynamic" # dynamic file path
    watch: true