name: Concat Stack's READMEs
on:
  push:
    paths:
      - 'stacks/*/README.md'  # watch changes in markdown files under stacks/* folders
  workflow_dispatch:

jobs:
  combine:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Combine Markdown files with parent folders as titles and fix links
        run: |
          output="stacks/README.md"
          > $output
          for file in stacks/*/README.md; do
            folder=$(basename "$(dirname "$file")")
            echo "# ${folder^}" >> $output
          
            # Use sed to update relative links by prepending the folder name
            # This transforms links like [link](authentik/README.md) to [link](administration/authentik/README.md)
            sed "s|\](\([^)]*\.md\))|\](${folder}/\1)|g" "$file" >> $output
            echo -e "\n" >> $output
          done

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add stacks/README.md
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-update combined README from stack READMEs"
            git push
          fi